[build]
  command        = "curl -sL https://github.com/CloudCannon/pagefind/releases/download/v1.5.1/pagefind-v1.5.1-x86_64-unknown-linux-musl.tar.gz | tar xz -C /usr/local/bin && python scripts/build.py"
  publish        = "site"

[build.environment]
  HUGO_VERSION   = "0.162.0"
  PYTHON_VERSION = "3.11"




#[build]
#  command        = "python scripts/build.py"
#  publish        = "site"
